import type {
  ClientSideToolV2Result,
  CurrentFileInfo,
  RefreshTabContextRequest,
  StreamCppRequest,
  StreamUnifiedChatRequest,
  StreamUnifiedChatRequestWithTools,
} from "./types/proto";

export const defaultRefreshTabContextPayload: RefreshTabContextRequest = {
  currentFile: {
    relativeWorkspacePath: "test.js",
    contents: "hello world",
    cursorPosition: {
      line: 0,
      column: 1,
    },
    dataframes: [],
    languageId: "",
    diagnostics: [],
    totalNumberOfLines: 0,
    contentsStartAtLine: 0,
    topChunks: [],
    fileVersion: 6,
    cellStartLines: [],
    cells: [],
    relyOnFilesync: false,
    workspaceRootPath: "/Users/somename/Desktop/test",
    lineEnding: "\n",
  },
  fileDiffHistories: [
    {
      fileName: "test.js",
      diffHistory: ["23-|\n23+|    \n"],
      diffHistoryTimestamps: [],
    },
  ],
  additionalFiles: [],
  timeSinceRequestStart: 10,
  timeAtRequestSend: Date.now(),
  workspaceId: "",
  supportsCpt: true,
  supportsCrlfCpt: true,
  clientTime: Date.now(),
  repositoryInfo: {
    repoName: process.env.REPO_NAME ?? "",
    repoOwner: process.env.REPO_OWNER ?? "",
    relativeWorkspacePath: ".",
    workspaceUris: {
      test: {
        $mid: 1,
        fsPath: "/Users/somename/Desktop/test",
        external: "file:///Users/somename/Desktop/test",
        path: "/Users/somename/Desktop/test",
        scheme: "file",
      },
    },
    orthogonalTransformSeed: 0,
    preferredEmbeddingModel: 0,
  },
};

export const defaultStreamCppCurrentFile: CurrentFileInfo = {
  relativeWorkspacePath: "Untitled-1",
  contents: "function ",
  cursorPosition: { line: 0, column: 1 },
  dataframes: [],
  languageId: "javascript",
  diagnostics: [],
  totalNumberOfLines: 0,
  contentsStartAtLine: 0,
  topChunks: [],
  fileVersion: 2,
  cellStartLines: [],
  cells: [],
  relyOnFilesync: false,
  workspaceRootPath: "",
  lineEnding: "\\n",
};

export const defaultStreamCppPayload: StreamCppRequest = {
  isDebug: false,
  giveDebugOutput: false,
  supportsCpt: false,
  supportsCrlfCpt: false,
  currentFile: defaultStreamCppCurrentFile,
  diffHistory: [],
  modelName: "fast",
  diffHistoryKeys: [],
  fileDiffHistories: [
    {
      fileName: "Untitled-1",
      diffHistory: ["1+| \\n"],
      diffHistoryTimestamps: [],
    },
  ],
  mergedDiffHistories: [],
  blockDiffPatches: [],
  contextItems: [],
  parameterHints: [],
  lspContexts: [],
  cppIntentInfo: { source: "line_change" },
  workspaceId: "",
  additionalFiles: [],
  clientTime: Date.now(),
  filesyncUpdates: [],
  timeSinceRequestStart: Date.now(),
  timeAtRequestSend: Date.now(),
  clientTimezoneOffset: new Date().getTimezoneOffset(),
  lspSuggestedItems: { suggestions: [] },
  codeResults: [],
};

export const defaultChatPanePayload: StreamUnifiedChatRequest = {
  conversation: [
    {
      text: "hey",
      type: "MESSAGE_TYPE_HUMAN",
      attachedCodeChunks: [],
      codebaseContextChunks: [],
      commits: [],
      pullRequests: [],
      gitDiffs: [],
      assistantSuggestedDiffs: [],
      interpreterResults: [],
      images: [],
      attachedFolders: [],
      approximateLintErrors: [],
      bubbleId: "7a93e7b6-07a5-4eb5-81dd-92c87d3ea3ec",
      attachedFoldersNew: [],
      lints: [],
      userResponsesToSuggestedCodeBlocks: [],
      relevantFiles: [],
      toolResults: [],
      notepads: [],
      capabilities: [],
      editTrailContexts: [],
      suggestedCodeBlocks: [],
      diffsForCompressingFiles: [],
      multiFileLinterErrors: [],
      diffHistories: [],
      recentlyViewedFiles: [],
      recentLocationsHistory: [],
      isAgentic: true,
      fileDiffTrajectories: [],
      existedSubsequentTerminalCommand: false,
      existedPreviousTerminalCommand: false,
      docsReferences: [],
      webReferences: [],
      attachedFoldersListDirResults: [],
      humanChanges: [],
      attachedHumanChanges: false,
      summarizedComposers: [],
      cursorRules: [],
      contextPieces: [],
      allThinkingBlocks: [],
      unifiedMode: "UNIFIED_MODE_CHAT",
      diffsSinceLastApply: [],
      deletedFiles: [],
      supportedTools: [
        "CLIENT_SIDE_TOOL_V2_READ_SEMSEARCH_FILES",
        "CLIENT_SIDE_TOOL_V2_RIPGREP_RAW_SEARCH",
        "CLIENT_SIDE_TOOL_V2_EDIT_FILE",
        "CLIENT_SIDE_TOOL_V2_EDIT_FILE_V2",
        "CLIENT_SIDE_TOOL_V2_FILE_SEARCH",
        "CLIENT_SIDE_TOOL_V2_SEMANTIC_SEARCH_FULL",
        "CLIENT_SIDE_TOOL_V2_DELETE_FILE",
        "CLIENT_SIDE_TOOL_V2_REAPPLY",
        "CLIENT_SIDE_TOOL_V2_RUN_TERMINAL_COMMAND_V2",
        "CLIENT_SIDE_TOOL_V2_WEB_SEARCH",
        "CLIENT_SIDE_TOOL_V2_KNOWLEDGE_BASE",
        "CLIENT_SIDE_TOOL_V2_DEEP_SEARCH",
        "CLIENT_SIDE_TOOL_V2_CREATE_PLAN",
        "CLIENT_SIDE_TOOL_V2_READ_PROJECT",
        "CLIENT_SIDE_TOOL_V2_UPDATE_PROJECT",
        "CLIENT_SIDE_TOOL_V2_FIX_LINTS",
        "CLIENT_SIDE_TOOL_V2_READ_LINTS",
        "CLIENT_SIDE_TOOL_V2_TASK",
        "CLIENT_SIDE_TOOL_V2_TODO_READ",
        "CLIENT_SIDE_TOOL_V2_TODO_WRITE",
        "CLIENT_SIDE_TOOL_V2_LIST_DIR_V2",
        "CLIENT_SIDE_TOOL_V2_READ_FILE_V2",
        "CLIENT_SIDE_TOOL_V2_GLOB_FILE_SEARCH",
        "CLIENT_SIDE_TOOL_V2_LIST_MCP_RESOURCES",
        "CLIENT_SIDE_TOOL_V2_READ_MCP_RESOURCE",
        "CLIENT_SIDE_TOOL_V2_CALL_MCP_TOOL",
        "CLIENT_SIDE_TOOL_V2_SWITCH_MODE",
      ],
      editToolSupportsSearchAndReplace: true,
      consoleLogs: [],
      richText:
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"hey","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
      knowledgeItems: [],
      uiElementPicked: [],
      documentationSelections: [],
      externalLinks: [],
      useWeb: false,
      projectLayouts: [],
      capabilityContexts: [],
      todos: [],
      requestId: "a5124ad4-604a-4e8f-954f-24d3240e9250",
      aiWebSearchResults: [],
      isPlanExecution: false,
      createdAt: "2025-12-26T03:30:56.810Z",
      modelInfo: {
        modelName: "composer-1",
      },
      isQuickSearchQuery: false,
      mcpDescriptors: [],
      workspaceProjectDir: "/Users/test/.cursor/projects/test-project",
      workspaceUris: ["file:///Users/test/Projects/test-project"],
    },
  ],
  allowLongFileScan: true,
  explicitContext: {
    context: "",
    rules: [],
    mcpInstructions: [],
  },
  canHandleFilenamesAfterLanguageIds: true,
  modelDetails: {
    modelName: "composer-1",
    azureState: {
      apiKey: "",
      baseUrl: "",
      deployment: "",
      useAzure: false,
    },
    maxMode: false,
  },
  documentationIdentifiers: [],
  externalLinks: [],
  diffsForCompressingFiles: [],
  multiFileLinterErrors: [],
  fileDiffHistories: [],
  useNewCompressionScheme: true,
  additionalRankedContext: [],
  quotes: [],
  isChat: false,
  conversationId: "b6147b37-4d9d-481b-bc22-5a9673bfb07e",
  repositoryInfo: {
    relativeWorkspacePath: ".",
    remoteUrls: [],
    remoteNames: [],
    repoName: "",
    repoOwner: "github|user_01J2XPB3D1NEWVTFVS2R05QSS7",
    isTracked: false,
    isLocal: false,
    orthogonalTransformSeed: 7891260764040897,
    preferredEmbeddingModel: "EMBEDDING_MODEL_UNSPECIFIED",
    workspaceUri: "",
  },
  repositoryInfoShouldQueryStaging: false,
  environmentInfo: {
    exthostPlatform: "darwin",
    exthostArch: "arm64",
    exthostRelease: "24.6.0",
    exthostShell: "/bin/zsh",
    localTimestamp: Date.now(),
    workspaceUris: ["file:///Users/test/Projects/test-project"],
    homeDirectory: "/Users/test",
    localTimezone: "Europe/London",
  },
  isAgentic: true,
  supportedTools: [
    "CLIENT_SIDE_TOOL_V2_READ_SEMSEARCH_FILES",
    "CLIENT_SIDE_TOOL_V2_RIPGREP_RAW_SEARCH",
    "CLIENT_SIDE_TOOL_V2_EDIT_FILE",
    "CLIENT_SIDE_TOOL_V2_EDIT_FILE_V2",
    "CLIENT_SIDE_TOOL_V2_FILE_SEARCH",
    "CLIENT_SIDE_TOOL_V2_SEMANTIC_SEARCH_FULL",
    "CLIENT_SIDE_TOOL_V2_DELETE_FILE",
    "CLIENT_SIDE_TOOL_V2_REAPPLY",
    "CLIENT_SIDE_TOOL_V2_RUN_TERMINAL_COMMAND_V2",
    "CLIENT_SIDE_TOOL_V2_WEB_SEARCH",
    "CLIENT_SIDE_TOOL_V2_KNOWLEDGE_BASE",
    "CLIENT_SIDE_TOOL_V2_DEEP_SEARCH",
    "CLIENT_SIDE_TOOL_V2_CREATE_PLAN",
    "CLIENT_SIDE_TOOL_V2_READ_PROJECT",
    "CLIENT_SIDE_TOOL_V2_UPDATE_PROJECT",
    "CLIENT_SIDE_TOOL_V2_FIX_LINTS",
    "CLIENT_SIDE_TOOL_V2_READ_LINTS",
    "CLIENT_SIDE_TOOL_V2_TASK",
    "CLIENT_SIDE_TOOL_V2_TODO_READ",
    "CLIENT_SIDE_TOOL_V2_TODO_WRITE",
    "CLIENT_SIDE_TOOL_V2_LIST_DIR_V2",
    "CLIENT_SIDE_TOOL_V2_READ_FILE_V2",
    "CLIENT_SIDE_TOOL_V2_GLOB_FILE_SEARCH",
    "CLIENT_SIDE_TOOL_V2_LIST_MCP_RESOURCES",
    "CLIENT_SIDE_TOOL_V2_READ_MCP_RESOURCE",
    "CLIENT_SIDE_TOOL_V2_CALL_MCP_TOOL",
    "CLIENT_SIDE_TOOL_V2_SWITCH_MODE",
  ],
  fullConversationHeadersOnly: [
    {
      bubbleId: "7a93e7b6-07a5-4eb5-81dd-92c87d3ea3ec",
      type: "MESSAGE_TYPE_HUMAN",
    },
  ],
  enableYoloMode: false,
  yoloPrompt: "",
  useUnifiedChatPrompt: false,
  mcpTools: [],
  useFullInputsContext: false,
  allowModelFallbacks: true,
  numberOfTimesShownFallbackModelWarning: 0,
  repositoryInfoShouldQueryProd: false,
  repoQueryAuthToken: "",
  isHeadless: false,
  unifiedMode: "UNIFIED_MODE_CHAT",
  toolsRequiringAcceptedReturn: [
    "CLIENT_SIDE_TOOL_V2_WEB_SEARCH",
    "CLIENT_SIDE_TOOL_V2_EDIT_FILE",
    "CLIENT_SIDE_TOOL_V2_EDIT_FILE_V2",
    "CLIENT_SIDE_TOOL_V2_BACKGROUND_COMPOSER_FOLLOWUP",
    "CLIENT_SIDE_TOOL_V2_SWITCH_MODE",
  ],
  shouldDisableTools: false,
  thinkingLevel: "THINKING_LEVEL_UNSPECIFIED",
  modeUsesAutoApply: false,
  unifiedModeName: "Ask",
  editToolSupportsSearchAndReplace: true,
  projectLayouts: [],
  supportsMermaidDiagrams: true,
  supportsGitIndex: false,
  isBackgroundComposer: false,
  forceIsNotDev: false,
  disableEditFileTimeout: false,
  replyingToRequestId: "",
  isQuickSearchQuery: false,
  isSpecMode: false,
  allowServerSideSemanticSearch: true,
  speculativeSummarizationEncryptionKey: "",
  workspaceFolders: [
    {
      uri: "file:///Users/test/Projects/test-project",
      name: "empty",
    },
  ],
  doesReadfileSupportImages: true,
  sandboxingSupportEnabled: true,
  enableTerminalFilePersistence: true,
  terminalsFolder: "/Users/test/.cursor/projects/test-project/terminals",
  hasMcpDescriptors: false,
  agentTranscriptsFolder:
    "/Users/test/.cursor/projects/test-project/agent-transcripts",
};
